language: java
sudo: false

notifications:
  email: false

cache:
  directories:
    - "${HOME}/.m2/"

before_install:
  - openssl aes-256-cbc -K $encrypted_d63810f507a9_key -iv $encrypted_d63810f507a9_iv
      -in retest-gmbh-gpg.asc.enc -out retest-gmbh-gpg.asc -d
  - gpg --fast-import retest-gmbh-gpg.asc

install: true

before_deploy: mvn package -DskipTests --settings .travis.settings.xml

deploy:
  provider: releases
  api_key: "${GH_TOKEN}"
  file_glob: true
  file: "./target/retest-model-*.jar"
  skip_cleanup: true
  on:
    tags: true
    branch: master
